version: '2'

# Maintainer: facugon
# this is used for development

services:
  theeye-redis:
    image: redis:latest
    container_name: theeye-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
       - ./redis:/data
    networks:
      - theeye

  theeye-mongodb:
    image: mongo:4.2
    container_name: theeye-mongodb
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - ./mongodb:/data/db
      - ./mongodump:/data/dump
    networks:
      - theeye   

  theeye-ldap:
    image: rroemhild/test-openldap
    container_name: theeye-ldap
    restart: always
    ports:
      - "389:389"
      - "636:636"
      - "10389:10389"
      - "10636:10636"
    networks:
      - theeye

  theeye-mailserver:
    image: djfarrelly/maildev
    container_name: theeye-mailserver
    restart: always
    ports:
      - "6083:80"
      - "6025:25"
    networks:
      - theeye

  theeye-nginx:
    #image: nginx
    image: imkulikov/nginx-sticky
    container_name: theeye-nginx
    restart: always
    volumes: 
      - ./nginx/etc/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/logs/:/var/log/nginx/
    ports:
      - "8080:80"
    networks:
      - theeye

  theeye-supervisor:
    build: ./sources/theeye-supervisor
    image: theeye-io/theeye-supervisor
    container_name: theeye-supervisor
    hostname: supervisor
    domainname: supervisor
    links:
      - theeye-gateway
    ports:
      - "60080:60080"
    volumes:
      - ./config/supervisor.js:/src/theeye/supervisor/config/production.js
      - ./scripts:/src/theeye/supervisor/uploads
    networks:
      - theeye
    environment:
      - DEBUG=*eye*err*
      - NODE_ENV=production
      - THEEYE_NODE_HOSTNAME=
      - MONITORING_DISABLED=
      - SCHEDULER_JOBS_DISABLED=
      - COMMANDER_DISABLED=
      - API_DISABLED=
      - PORT=60080

  theeye-gateway:
    build: ./sources/theeye-gateway/
    image: theeye-io/theeye-gateway
    container_name: theeye-gateway
    hostname: gateway
    domainname: gateway
    links:
      - theeye-mongodb
      - theeye-redis
      - theeye-ldap
      - theeye-mailserver
    ports:
      #- "9229:9229"
      - "6080:6080"
    volumes:
      - ./config/gateway.json:/src/theeye/gateway/server/config/production.json
      - ./web:/src/theeye/gateway/client/dist
    networks:
      - theeye
    restart: always
    environment:
      - DEBUG=*eye*err*
      - THEEYE_CONFIG_ENCRYPTED=false
      - THEEYE_CONFIG_ENCRYPTED_IV=6c888d53cd9e5d32d4a428777e6a35e0
      - THEEYE_CONFIG_ENCRYPTED_SECRET=7d571e7a5e4d9375cf5ec6360247ee018648efe1eccba5894ee6659db626b5dd
      - THEEYE_CONFIG_ENCRYPTED_ALGORITHM=aes-256-ctr
      - THEEYE_NODE_HOSTNAME=theeye
      - NODE_ENV=production
      - PORT=6080
    #command:
    #  - 'node'
    #  - '--inspect=0.0.0.0:9229'
    #  - './server'

  theeye-agent:
    image: theeye/theeye-agent:development
    container_name: theeye-agent
    networks:
      - theeye
    restart: always
    links:
      - theeye-supervisor
      - theeye-gateway
    volumes:
      - ./agent/config.js:/src/theeye/agent/config/production.js
      - ./agent/downloads:/src/theeye/agent/downloads
      - ./agent/logs:/src/theeye/agent/logs
    environment:
      - DEBUG=*eye*err*
      - NODE_ENV=production
      - THEEYE_SUPERVISOR_CLIENT_ID=da4b4e840c107ce9a0f4d28961b71e070e3b80e2
      - THEEYE_SUPERVISOR_CLIENT_SECRET=e4304720b3be25551cbb2b99c775f124e3d9ad84
      - THEEYE_SUPERVISOR_CLIENT_CUSTOMER=theeye
      - THEEYE_SUPERVISOR_API_URL=http://theeye-supervisor:60080
      - THEEYE_CLIENT_HOSTNAME=theeye
        #- THEEYE_AGENT_SCRIPT_PATH='/opt/theeye-agent/scripts'

  theeye-web:
    image: theeye-io/theeye-web
    build:
      context: ./sources/theeye-web
      dockerfile: Dockerfile
      args:
        - NODE_ENV=docker
    container_name: theeye-web

networks:
   theeye:
      external:
         name: theeye
